"use client"

import React from 'react';
import { Card, CardContent } from '@/components/ui/card';

interface DynamicReactRendererProps {
  componentCode: string;
}

/**
 * A component that displays the React component code with syntax highlighting
 */
export function DynamicReactRenderer({ componentCode }: DynamicReactRendererProps) {
  // Extract the component name from the code for display purposes
  const exportMatch = componentCode?.match(/export\s+function\s+(\w+)/);
  const componentName = exportMatch ? exportMatch[1] : 'GeneratedComponent';
  
  return (
    <Card className="w-full bg-black/40 border-[#00FFFF]/20 shadow-[0_0_15px_rgba(0,255,255,0.2)]">
      <CardContent className="p-6">
        <div className="flex justify-between items-center mb-4">
          <h3 className="text-xl font-semibold text-[#00FFFF]">Generated React Component: {componentName}</h3>
          <div className="flex space-x-2">
            <button 
              onClick={() => {
                const dataStr = "data:text/jsx;charset=utf-8," + encodeURIComponent(componentCode);
                const downloadAnchorNode = document.createElement('a');
                downloadAnchorNode.setAttribute("href", dataStr);
                downloadAnchorNode.setAttribute("download", `${componentName}.tsx`);
                document.body.appendChild(downloadAnchorNode);
                downloadAnchorNode.click();
                downloadAnchorNode.remove();
              }}
              className="px-3 py-1 bg-[#00FFFF]/10 hover:bg-[#00FFFF]/20 text-[#00FFFF] text-sm rounded border border-[#00FFFF]/30"
            >
              Download
            </button>
            <button
              onClick={() => navigator.clipboard.writeText(componentCode)}
              className="px-3 py-1 bg-[#00FFFF]/10 hover:bg-[#00FFFF]/20 text-[#00FFFF] text-sm rounded border border-[#00FFFF]/30"
            >
              Copy
            </button>
          </div>
        </div>
        
        <div className="relative">
          <pre className="bg-gray-900 p-4 rounded-md text-[#00FFFF]/90 text-sm overflow-auto max-h-[500px] font-mono">
            {componentCode}
          </pre>
          <div className="absolute top-0 right-0 bg-gray-800 text-xs text-gray-400 px-2 py-1 rounded-bl">
            React Component
          </div>
        </div>
        
        <div className="mt-4 p-4 bg-gray-900/50 rounded-md border border-[#00FFFF]/10">
          <p className="text-gray-300 text-sm">
            This is the React component code generated by Gemini. To use it in your project:
          </p>
          <ol className="text-gray-300 text-sm mt-2 list-decimal list-inside">
            <li>Download the component file</li>
            <li>Add it to your project</li>
            <li>Import and use it in your application</li>
          </ol>
        </div>
      </CardContent>
    </Card>
  );
}
